name: Launch makepkg
description: Launch makepkg in an archlinux-like OS.
inputs:
  builddir:
    description: The directory is relative to github.workspace and contains PKGBUILD.
    required: true
  args:
    description: The arguments to makepkg.
    required: false
  env:
    description: The extra environments splitted in newline.
    required: false
  stdout:
    description: Where to save stdout.
    required: false
  repo:
    description: Custom repository to storage extra depends
    required: false
  updatepkgbuild:
    description: If sync updated PKGBUILD to builddir. Useful when you just bump pkgver.
    required: false
    default: false
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.args }}
